// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.0
// source: backend.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	// ListResources RPC for listing resources with pagination.
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, "/backend.ResourceService/ListResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility
type ResourceServiceServer interface {
	// ListResources RPC for listing resources with pagination.
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResourceServiceServer struct {
}

func (UnimplementedResourceServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.ResourceService/ListResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResources",
			Handler:    _ResourceService_ListResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

// AnimalRankingServiceClient is the client API for AnimalRankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnimalRankingServiceClient interface {
	// ListAnimalRankings RPC for listing animal rankings with pagination.
	ListAnimalRankings(ctx context.Context, in *ListAnimalRankingsRequest, opts ...grpc.CallOption) (*ListAnimalRankingsResponse, error)
}

type animalRankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimalRankingServiceClient(cc grpc.ClientConnInterface) AnimalRankingServiceClient {
	return &animalRankingServiceClient{cc}
}

func (c *animalRankingServiceClient) ListAnimalRankings(ctx context.Context, in *ListAnimalRankingsRequest, opts ...grpc.CallOption) (*ListAnimalRankingsResponse, error) {
	out := new(ListAnimalRankingsResponse)
	err := c.cc.Invoke(ctx, "/backend.AnimalRankingService/ListAnimalRankings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimalRankingServiceServer is the server API for AnimalRankingService service.
// All implementations must embed UnimplementedAnimalRankingServiceServer
// for forward compatibility
type AnimalRankingServiceServer interface {
	// ListAnimalRankings RPC for listing animal rankings with pagination.
	ListAnimalRankings(context.Context, *ListAnimalRankingsRequest) (*ListAnimalRankingsResponse, error)
	mustEmbedUnimplementedAnimalRankingServiceServer()
}

// UnimplementedAnimalRankingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnimalRankingServiceServer struct {
}

func (UnimplementedAnimalRankingServiceServer) ListAnimalRankings(context.Context, *ListAnimalRankingsRequest) (*ListAnimalRankingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnimalRankings not implemented")
}
func (UnimplementedAnimalRankingServiceServer) mustEmbedUnimplementedAnimalRankingServiceServer() {}

// UnsafeAnimalRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnimalRankingServiceServer will
// result in compilation errors.
type UnsafeAnimalRankingServiceServer interface {
	mustEmbedUnimplementedAnimalRankingServiceServer()
}

func RegisterAnimalRankingServiceServer(s grpc.ServiceRegistrar, srv AnimalRankingServiceServer) {
	s.RegisterService(&AnimalRankingService_ServiceDesc, srv)
}

func _AnimalRankingService_ListAnimalRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnimalRankingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalRankingServiceServer).ListAnimalRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.AnimalRankingService/ListAnimalRankings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalRankingServiceServer).ListAnimalRankings(ctx, req.(*ListAnimalRankingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnimalRankingService_ServiceDesc is the grpc.ServiceDesc for AnimalRankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnimalRankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.AnimalRankingService",
	HandlerType: (*AnimalRankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAnimalRankings",
			Handler:    _AnimalRankingService_ListAnimalRankings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
