package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"
)

// Resource represents a row from 'platform.resources'.
type Resource struct {
	ID        int       `json:"id"`         // id
	UUID      string    `json:"uuid"`       // uuid
	Name      string    `json:"name"`       // name
	CreatedAt time.Time `json:"created_at"` // created_at
	UpdatedAt time.Time `json:"updated_at"` // updated_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Resource] exists in the database.
func (r *Resource) Exists() bool {
	return r._exists
}

// Deleted returns true when the [Resource] has been marked for deletion
// from the database.
func (r *Resource) Deleted() bool {
	return r._deleted
}

// Insert inserts the [Resource] to the database.
func (r *Resource) Insert(ctx context.Context, db DB) error {
	switch {
	case r._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case r._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO platform.resources (` +
		`uuid, name, created_at, updated_at` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`
	// run
	logf(sqlstr, r.UUID, r.Name, r.CreatedAt, r.UpdatedAt)
	res, err := db.ExecContext(ctx, sqlstr, r.UUID, r.Name, r.CreatedAt, r.UpdatedAt)
	if err != nil {
		return logerror(err)
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return logerror(err)
	} // set primary key
	r.ID = int(id)
	// set exists
	r._exists = true
	return nil
}

// Update updates a [Resource] in the database.
func (r *Resource) Update(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case r._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE platform.resources SET ` +
		`uuid = ?, name = ?, created_at = ?, updated_at = ? ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, r.UUID, r.Name, r.CreatedAt, r.UpdatedAt, r.ID)
	if _, err := db.ExecContext(ctx, sqlstr, r.UUID, r.Name, r.CreatedAt, r.UpdatedAt, r.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Resource] to the database.
func (r *Resource) Save(ctx context.Context, db DB) error {
	if r.Exists() {
		return r.Update(ctx, db)
	}
	return r.Insert(ctx, db)
}

// Upsert performs an upsert for [Resource].
func (r *Resource) Upsert(ctx context.Context, db DB) error {
	switch {
	case r._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO platform.resources (` +
		`id, uuid, name, created_at, updated_at` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`uuid = VALUES(uuid), name = VALUES(name), created_at = VALUES(created_at), updated_at = VALUES(updated_at)`
	// run
	logf(sqlstr, r.ID, r.UUID, r.Name, r.CreatedAt, r.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID, r.UUID, r.Name, r.CreatedAt, r.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Delete deletes the [Resource] from the database.
func (r *Resource) Delete(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return nil
	case r._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM platform.resources ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, r.ID)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	r._deleted = true
	return nil
}

// ResourceKeysetPage retrieves a page of [Resource] records using keyset pagination with dynamic filtering.
//
// The keyset pagination retrieves results after or before a specific value (`key`)
// for a given column (`column`) with a limit (`limit`) and order (`ASC` or `DESC`).
//
// If `order` is `ASC`, it retrieves records where the value of `column` is greater than `key`.
// If `order` is `DESC`, it retrieves records where the value of `column` is less than `key`.
//
// Filters are dynamically provided via a `filters` map, where keys are column names and values are either single values or slices for `IN` clauses.
func ResourceKeysetPage(ctx context.Context, db DB, column string, key interface{}, limit int, order string, filters map[string]interface{}) ([]*Resource, *Resource, error) {
	if order != "ASC" && order != "DESC" {
		return nil, nil, fmt.Errorf("invalid order: %s", order)
	}

	// Start building the query
	query := fmt.Sprintf(
		`SELECT * FROM resources 
         WHERE %s %s ?`,
		column, condition(order), // Ensure this is returning a valid operator
	)

	// Arguments for the query
	args := []interface{}{key}

	// Dynamically add filters from the `filters` map to the query
	for field, value := range filters {
		switch v := value.(type) {
		case []int:
			if len(v) > 0 {
				placeholders := make([]string, len(v))
				for i := range v {
					placeholders[i] = "?"
					args = append(args, v[i])
				}
				query += fmt.Sprintf(" AND %s IN (%s)", field, strings.Join(placeholders, ", "))
			}
		case []string:
			if len(v) > 0 {
				placeholders := make([]string, len(v))
				for i := range v {
					placeholders[i] = "?"
					args = append(args, v[i])
				}
				query += fmt.Sprintf(" AND %s IN (%s)", field, strings.Join(placeholders, ", "))
			}
		default:
			query += fmt.Sprintf(" AND %s = ?", field)
			args = append(args, value)
		}
	}

	// Finalize the query with the order and limit
	query += fmt.Sprintf(" ORDER BY %s %s LIMIT ?", column, order)
	args = append(args, limit)

	// Log the final query for debugging purposes
	log.Printf("Executing query: %s with args: %v", query, args)

	// Execute the query
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, nil, logerror(err)
	}
	defer rows.Close()

	var results []*Resource
	var lastItem *Resource // Variable to store the last item

	for rows.Next() {
		r := Resource{
			_exists: true,
		}
		if err := rows.Scan(
			&r.ID, &r.UUID, &r.Name, &r.CreatedAt, &r.UpdatedAt,
		); err != nil {
			return nil, nil, logerror(err)
		}
		results = append(results, &r)
	}

	// Check for errors during row iteration.
	if err := rows.Err(); err != nil {
		return nil, nil, logerror(err)
	}

	// If we have results, set the lastItem to the last element in results.
	if len(results) > 0 {
		lastItem = results[len(results)-1]
	}

	return results, lastItem, nil
}

// ResourceByID retrieves a row from 'platform.resources' as a [Resource].
//
// Generated from index 'resources_id_pkey'.
func ResourceByID(ctx context.Context, db DB, id int) (*Resource, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, uuid, name, created_at, updated_at ` +
		`FROM platform.resources ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, id)
	r := Resource{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&r.ID, &r.UUID, &r.Name, &r.CreatedAt, &r.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &r, nil
}

// ResourceByUUID retrieves a row from 'platform.resources' as a [Resource].
//
// Generated from index 'uuid'.
func ResourceByUUID(ctx context.Context, db DB, uuid string) (*Resource, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, uuid, name, created_at, updated_at ` +
		`FROM platform.resources ` +
		`WHERE uuid = ?`
	// run
	logf(sqlstr, uuid)
	r := Resource{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, uuid).Scan(&r.ID, &r.UUID, &r.Name, &r.CreatedAt, &r.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &r, nil
}
